### ISSUE TITLE
[Feature request] Is it possible to get a current status of the notification setting?

### ISSUE THREAD

**Issue by thepra** [Append-IT/Blazor.Notifications#6]
Something like `await NotificationService.GetCurrentNotificationStatus()` which returns the `PermissionType` enum?

**Comment by MrGeneric** [comment]
Do you still need this?

**Comment by thepra** [comment]
yep, I could improve the user experience given that I could figure out what's the current state.

**Comment by MrGeneric** [comment]
Check my fork. Hopefully I've understood your request. 

[Blazor.Notifications](https://github.com/MrGeneric/Blazor.Notifications)

**Comment by thepra** [comment]
I see, yes a string should be good enough(could be better with the enum).

**Comment by vertonghenb** [comment]
Fixed, it's not possible using the Getter:
```cs
NotificationService.PermissionStatus
```
