### ISSUE TITLE
Make the library offline capable for proper PWA functioning

### ISSUE THREAD

**Issue by thepra** [Append-IT/Blazor.Notifications#8]
Today, through tests, I figured out that the dependency injection doesn't work for this library when the client is offline and is calling the dependency injection of `INotificationService`, like in this error:
>Microsoft.JSInterop.JSException: error loading dynamically imported module at Microsoft.JSInterop.JSRuntime.d__15`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext() at Append.Blazor.Notifications.NotificationService.IsSupportedByBrowserAsync() at <redacted>.Client.Components.Subpages.GeneralSettings.OnInitializedAsync()

Could you make it so that the loading of the js library is possible from the beginning without requiring it afterwards?
![immagine](https://user-images.githubusercontent.com/7032509/138505807-77f845e1-9bbf-491d-9bdb-d26f41c64f05.png)

I know this is a solution for library loading optimization and seem cool but given that PWA's are supposed to be capable to work offline and given this optimization, that library will never load when reaching a page that does need the notification service but never happened to cache it in the first place.

**Comment by vertonghenb** [comment]
Hi @thepra 
Sorry for getting back to you so late! Interesting idea, but I think it can be solved in a more PWA-way and not impact actual website implementation (only load the file when you're using it). 

Jeremy Likeness posted a small article on how he handles offline cache strategy when the file needs to be there on install. I believe in implementing it this way is more interesting. In a PWA scenario you can specify the file to download instantly to offer offline support, on initial load on the website on the other hand, the file will only be downloaded when it's needed.

The following article should point you in the right way:
https://blog.jeremylikness.com/blog/implement-progressive-web-app-hugo/
